import { createHash, randomUUID } from 'node:crypto';
import { mkdir, readFile, writeFile, access } from 'node:fs/promises';
import path from 'node:path';

export const WORKER_ID = 'korako-public-worker-v0.1';
export const VERIFIER_ID = 'korako-public-independent-verifier-v0.1';
export const APPROVAL_TOKEN = 'APPROVE_PUBLIC_GOLDEN_V0_1';

function nowIso() { return new Date().toISOString(); }
function sha256(text) { return createHash('sha256').update(text).digest('hex'); }
async function exists(filePath) { try { await access(filePath); return true; } catch { return false; } }
async function persist(statePath, state) { await mkdir(path.dirname(statePath), { recursive: true }); await writeFile(statePath, `${JSON.stringify(state, null, 2)}\n`, 'utf8'); }
function appendHistory(state, event, detail = {}) { state.history.push({ at: nowIso(), event, ...detail }); }

export async function createRun({ workspace, goal, inputPath, artifactPath }) {
  const statePath = path.join(workspace, 'state.json');
  const state = {
    schema: 'KORAKO-PUBLIC-GOLDEN-RUN-0.1', run_id: randomUUID(), goal, status: 'PLANNED',
    plan: { steps: ['read bounded local input','create deterministic markdown artifact','capture content hash and provenance','verify artifact with independent verifier identity','persist terminal state'], input_path: inputPath, artifact_path: artifactPath },
    authority: { required: true, preview: { effect: 'write one markdown artifact inside the provided workspace', external_network: false, destructive_actions: false }, approved: false, approval_fingerprint: null },
    execution: null, evidence: null, verification: null, recovery: { count: 0 },
    metrics: { human_decisions: 0, human_postman_transfers: 0, system_stage_transitions: 1 }, history: []
  };
  appendHistory(state, 'PLAN_CREATED'); await persist(statePath, state); return { statePath, state };
}

export async function loadRun(statePath) { return JSON.parse(await readFile(statePath, 'utf8')); }

export async function authorizeRun(statePath, approvalToken) {
  const state = await loadRun(statePath);
  if (state.status !== 'PLANNED' && state.status !== 'RECOVERING') throw new Error(`AUTHORITY_INVALID_STATE:${state.status}`);
  if (approvalToken !== APPROVAL_TOKEN) { appendHistory(state, 'AUTHORITY_REJECTED'); await persist(statePath, state); throw new Error('HUMAN_GATE_REQUIRED'); }
  state.authority.approved = true; state.authority.approval_fingerprint = sha256(approvalToken); state.metrics.human_decisions += 1; state.status = 'AUTHORIZED'; state.metrics.system_stage_transitions += 1;
  appendHistory(state, 'AUTHORITY_APPROVED'); await persist(statePath, state); return state;
}

export async function executeRun(statePath) {
  const state = await loadRun(statePath);
  if (!state.authority?.approved || state.status !== 'AUTHORIZED') throw new Error('EXECUTION_BLOCKED_BY_AUTHORITY');
  const source = await readFile(state.plan.input_path, 'utf8');
  const lines = source.split(/\r?\n/).map((line) => line.trim()).filter(Boolean);
  const artifact = ['# Korako Public Golden Artifact','',`Goal: ${state.goal}`,'','## Structured input','',...lines.map((line) => `- ${line}`),'',`Generated by: ${WORKER_ID}`,''].join('\n');
  await mkdir(path.dirname(state.plan.artifact_path), { recursive: true }); await writeFile(state.plan.artifact_path, artifact, 'utf8');
  state.execution = { worker_id: WORKER_ID, bounded: true, external_network: false, destructive_actions: false, artifact_path: state.plan.artifact_path };
  state.evidence = { artifact_sha256: sha256(artifact), artifact_bytes: Buffer.byteLength(artifact), provenance: WORKER_ID, changed_files: [state.plan.artifact_path] };
  state.status = 'EXECUTED'; state.metrics.system_stage_transitions += 1; appendHistory(state, 'EXECUTION_COMPLETED', { artifact_sha256: state.evidence.artifact_sha256 }); await persist(statePath, state); return state;
}

export async function verifyRun(statePath) {
  const state = await loadRun(statePath);
  if (state.status !== 'EXECUTED') throw new Error(`VERIFICATION_INVALID_STATE:${state.status}`);
  if (state.execution?.worker_id === VERIFIER_ID) throw new Error('SELF_VERIFICATION_FORBIDDEN');
  if (!(await exists(state.plan.artifact_path))) throw new Error('ARTIFACT_MISSING');
  const artifact = await readFile(state.plan.artifact_path, 'utf8'); const actualHash = sha256(artifact);
  const checks = { authority_present: state.authority.approved === true, worker_is_bounded: state.execution?.bounded === true, no_external_network: state.execution?.external_network === false, artifact_hash_matches: actualHash === state.evidence?.artifact_sha256, provenance_matches_worker: state.evidence?.provenance === state.execution?.worker_id, independent_verifier: VERIFIER_ID !== state.execution?.worker_id, exactly_one_changed_file: state.evidence?.changed_files?.length === 1 };
  const pass = Object.values(checks).every(Boolean);
  state.verification = { verifier_id: VERIFIER_ID, verdict: pass ? 'PASS' : 'FAIL', checks }; state.status = pass ? 'VERIFIED' : 'VERIFICATION_FAILED'; state.metrics.system_stage_transitions += 1; appendHistory(state, 'VERIFICATION_COMPLETED', { verdict: state.verification.verdict }); await persist(statePath, state);
  if (!pass) throw new Error('VERIFICATION_FAILED'); return state;
}

export async function markInterrupted(statePath, reason = 'SIMULATED_INTERRUPTION') { const state = await loadRun(statePath); if (state.status !== 'AUTHORIZED') throw new Error(`INTERRUPTION_INVALID_STATE:${state.status}`); state.status = 'INTERRUPTED'; appendHistory(state, 'RUN_INTERRUPTED', { reason }); await persist(statePath, state); return state; }
export async function recoverRun(statePath) { const state = await loadRun(statePath); if (state.status !== 'INTERRUPTED') throw new Error(`RECOVERY_INVALID_STATE:${state.status}`); state.status = 'RECOVERING'; state.recovery.count += 1; appendHistory(state, 'RECOVERY_STARTED'); await persist(statePath, state); state.status = 'AUTHORIZED'; appendHistory(state, 'RECOVERY_RESTORED_AUTHORIZED_CHECKPOINT'); await persist(statePath, state); return state; }
export async function assertTerminalVerified(statePath) { const state = await loadRun(statePath); if (state.status !== 'VERIFIED' || state.verification?.verdict !== 'PASS') throw new Error('RUN_NOT_VERIFIED'); return state; }
